/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsAgentKeyRouteImport } from './routes/agents/$agentKey'
import { Route as InstructionsEditRouteImport } from './routes/instructions.edit'
import { Route as PresetsIndexRouteImport } from './routes/presets/index'
import { Route as PresetsPresetIdRouteImport } from './routes/presets/$presetId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as AgentsAgentKeyEditRouteImport } from './routes/agents_.$agentKey.edit'
import { Route as LibrarySkillIdEditRouteImport } from './routes/library_.$skillId.edit'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects_.$projectId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentKeyRoute = AgentsAgentKeyRouteImport.update({
  id: '/agents/$agentKey',
  path: '/agents/$agentKey',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsEditRoute = InstructionsEditRouteImport.update({
  id: '/instructions/edit',
  path: '/instructions/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsIndexRoute = PresetsIndexRouteImport.update({
  id: '/presets/',
  path: '/presets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsPresetIdRoute = PresetsPresetIdRouteImport.update({
  id: '/presets/$presetId',
  path: '/presets/$presetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentKeyEditRoute = AgentsAgentKeyEditRouteImport.update({
  id: '/agents_/$agentKey/edit',
  path: '/agents/$agentKey/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySkillIdEditRoute = LibrarySkillIdEditRouteImport.update({
  id: '/library_/$skillId/edit',
  path: '/library/$skillId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects_/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentKey': typeof AgentsAgentKeyRoute
  '/instructions/edit': typeof InstructionsEditRoute
  '/presets/$presetId': typeof PresetsPresetIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/presets/': typeof PresetsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/agents/$agentKey/edit': typeof AgentsAgentKeyEditRoute
  '/library/$skillId/edit': typeof LibrarySkillIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentKey': typeof AgentsAgentKeyRoute
  '/instructions/edit': typeof InstructionsEditRoute
  '/presets/$presetId': typeof PresetsPresetIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/agents': typeof AgentsIndexRoute
  '/presets': typeof PresetsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/agents/$agentKey/edit': typeof AgentsAgentKeyEditRoute
  '/library/$skillId/edit': typeof LibrarySkillIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/install': typeof InstallRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/agents/$agentKey': typeof AgentsAgentKeyRoute
  '/instructions/edit': typeof InstructionsEditRoute
  '/presets/$presetId': typeof PresetsPresetIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/presets/': typeof PresetsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/agents_/$agentKey/edit': typeof AgentsAgentKeyEditRoute
  '/library_/$skillId/edit': typeof LibrarySkillIdEditRoute
  '/projects_/$projectId/edit': typeof ProjectsProjectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/install'
    | '/library'
    | '/settings'
    | '/agents/$agentKey'
    | '/instructions/edit'
    | '/presets/$presetId'
    | '/projects/$projectId'
    | '/agents/'
    | '/presets/'
    | '/projects/'
    | '/agents/$agentKey/edit'
    | '/library/$skillId/edit'
    | '/projects/$projectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/install'
    | '/library'
    | '/settings'
    | '/agents/$agentKey'
    | '/instructions/edit'
    | '/presets/$presetId'
    | '/projects/$projectId'
    | '/agents'
    | '/presets'
    | '/projects'
    | '/agents/$agentKey/edit'
    | '/library/$skillId/edit'
    | '/projects/$projectId/edit'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/install'
    | '/library'
    | '/settings'
    | '/agents/$agentKey'
    | '/instructions/edit'
    | '/presets/$presetId'
    | '/projects/$projectId'
    | '/agents/'
    | '/presets/'
    | '/projects/'
    | '/agents_/$agentKey/edit'
    | '/library_/$skillId/edit'
    | '/projects_/$projectId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  InstallRoute: typeof InstallRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  AgentsAgentKeyRoute: typeof AgentsAgentKeyRoute
  InstructionsEditRoute: typeof InstructionsEditRoute
  PresetsPresetIdRoute: typeof PresetsPresetIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  PresetsIndexRoute: typeof PresetsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AgentsAgentKeyEditRoute: typeof AgentsAgentKeyEditRoute
  LibrarySkillIdEditRoute: typeof LibrarySkillIdEditRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentKey': {
      id: '/agents/$agentKey'
      path: '/agents/$agentKey'
      fullPath: '/agents/$agentKey'
      preLoaderRoute: typeof AgentsAgentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions/edit': {
      id: '/instructions/edit'
      path: '/instructions/edit'
      fullPath: '/instructions/edit'
      preLoaderRoute: typeof InstructionsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets/': {
      id: '/presets/'
      path: '/presets'
      fullPath: '/presets/'
      preLoaderRoute: typeof PresetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets/$presetId': {
      id: '/presets/$presetId'
      path: '/presets/$presetId'
      fullPath: '/presets/$presetId'
      preLoaderRoute: typeof PresetsPresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents_/$agentKey/edit': {
      id: '/agents_/$agentKey/edit'
      path: '/agents/$agentKey/edit'
      fullPath: '/agents/$agentKey/edit'
      preLoaderRoute: typeof AgentsAgentKeyEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$skillId/edit': {
      id: '/library_/$skillId/edit'
      path: '/library/$skillId/edit'
      fullPath: '/library/$skillId/edit'
      preLoaderRoute: typeof LibrarySkillIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/edit': {
      id: '/projects_/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  InstallRoute: InstallRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  AgentsAgentKeyRoute: AgentsAgentKeyRoute,
  InstructionsEditRoute: InstructionsEditRoute,
  PresetsPresetIdRoute: PresetsPresetIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  PresetsIndexRoute: PresetsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AgentsAgentKeyEditRoute: AgentsAgentKeyEditRoute,
  LibrarySkillIdEditRoute: LibrarySkillIdEditRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
