import type { AgentDefinition } from "./agents";

/**
 * Agents added in September 2026. Every folder and variable here is stated in the agent's own
 * documentation or source code, checked then; `reload` only where that source says when skills
 * are picked up.
 */
export const MORE_AGENTS: readonly AgentDefinition[] = [
  {
    key: "aider_desk",
    displayName: "AiderDesk",
    skillsDir: ".aider-desk/skills",
    detectDir: ".aider-desk",
    reload: { when: "live" },
  },
  {
    key: "autohand_code",
    displayName: "Autohand Code CLI",
    skillsDir: ".autohand/skills",
    detectDir: ".autohand",
    extraScanDirs: [".codex/skills", ".claude/skills", ".agent/skills", ".agents/skills"],
    projectExtraScanDirs: [".claude/skills", "skills", ".agent/skills", ".agents/skills"],
    recursiveScan: true,
    homeEnv: { variable: "AUTOHAND_HOME", skillsDir: "skills" },
    reload: { when: "new_session" },
  },
  {
    key: "codearts_agent",
    displayName: "CodeArts Agent",
    skillsDir: ".codeartsdoer/skills",
    detectDir: ".codeartsdoer",
    reload: { when: "live" },
  },
  {
    key: "devin_terminal",
    displayName: "Devin for Terminal",
    skillsDir: ".config/devin/skills",
    detectDir: ".config/devin",
    projectSkillsDir: ".devin/skills",
    extraScanDirs: [".agents/skills", ".codeium/windsurf/skills"],
    projectExtraScanDirs: [".agents/skills", ".windsurf/skills"],
  },
  {
    key: "dexto",
    displayName: "Dexto",
    skillsDir: ".agents/skills",
    detectDir: ".dexto",
    extraScanDirs: [".dexto/skills"],
    projectExtraScanDirs: [".dexto/skills", "skills"],
    reload: { when: "live" },
  },
  {
    key: "forgecode",
    displayName: "ForgeCode",
    skillsDir: ".forge/skills",
    detectDir: ".forge",
    extraScanDirs: [".agents/skills"],
    homeEnv: { variable: "FORGE_CONFIG", skillsDir: "skills" },
    reload: { when: "new_session" },
  },
  {
    key: "fx",
    displayName: "fx",
    skillsDir: ".fx/skills",
    detectDir: ".fx",
    projectSkillsDir: ".agents/skills",
    extraScanDirs: [
      ".config/opencode/skills",
      ".codex/skills",
      ".claude/skills",
      ".agents/skills",
      ".claw/skills",
    ],
    projectExtraScanDirs: [
      "skills",
      ".opencode/skills",
      ".codex/skills",
      ".claude/skills",
      ".claw/skills",
    ],
  },
  {
    key: "jazz",
    displayName: "Jazz",
    skillsDir: ".jazz/skills",
    detectDir: ".jazz",
    projectSkillsDir: "skills",
    extraScanDirs: [".agents/skills"],
    category: "assistant",
    homeEnv: { variable: "JAZZ_HOME", skillsDir: "skills" },
    reload: { when: "new_session" },
  },
  {
    key: "kimchi",
    displayName: "Kimchi",
    skillsDir: ".config/kimchi/harness/skills",
    detectDir: ".config/kimchi",
    projectSkillsDir: ".kimchi/skills",
    extraScanDirs: [
      ".agents/skills",
      ".claude/skills",
      ".cursor/skills",
      ".copilot/skills",
      ".github/skills",
      ".factory/skills",
      ".gemini/skills",
      ".warp/skills",
      ".codex/skills",
      ".pi/agent/skills",
    ],
    projectExtraScanDirs: [
      ".agents/skills",
      ".claude/skills",
      ".cursor/skills",
      ".copilot/skills",
      ".github/skills",
      ".factory/skills",
      ".gemini/skills",
      ".warp/skills",
      ".codex/skills",
    ],
    reload: { when: "new_session" },
  },
  {
    key: "minimax_code",
    displayName: "MiniMax Code",
    skillsDir: ".minimax/skills",
    detectDir: ".minimax",
    extraScanDirs: [".claude/skills", ".codex/skills", ".agents/skills"],
    projectExtraScanDirs: [".claude/skills", ".agents/skills"],
    homeEnv: { variable: "MINIMAX_DATA_DIR", skillsDir: "skills" },
  },
  {
    key: "posit_assistant",
    displayName: "Posit Assistant",
    skillsDir: ".posit/assistant/skills",
    detectDir: ".posit/assistant",
    extraScanDirs: [".agents/skills"],
    projectExtraScanDirs: [".agents/skills"],
    reload: { when: "new_session" },
  },
  {
    key: "reasonix",
    displayName: "Reasonix",
    skillsDir: ".reasonix/skills",
    detectDir: ".reasonix",
    extraScanDirs: [".agents/skills", ".agent/skills", ".claude/skills"],
    projectExtraScanDirs: [".agents/skills", ".agent/skills", ".claude/skills"],
    homeEnv: { variable: "REASONIX_HOME", skillsDir: "skills" },
    reload: { when: "new_session", command: "/reload" },
  },
  {
    key: "rovo_dev",
    displayName: "Rovo Dev",
    skillsDir: ".rovodev/skills",
    detectDir: ".rovodev",
    extraScanDirs: [".agents/skills"],
    projectExtraScanDirs: [".agents/skills"],
  },
  {
    key: "tinycloud",
    displayName: "Tinycloud",
    skillsDir: ".tinycloud/skills",
    detectDir: ".tinycloud",
    category: "assistant",
    homeEnv: { variable: "TINYCLOUD_HOME", skillsDir: "skills" },
    reload: { when: "restart" },
  },
  {
    key: "zed",
    displayName: "Zed",
    skillsDir: ".agents/skills",
    detectDir: ".config/zed",
    reload: { when: "live" },
  },
];
