import { chmodSync, copyFileSync, readFileSync, renameSync, truncateSync } from "node:fs";
import { join } from "node:path";
import { APP_NAME, CLI_BINARY_NAME, type CliStatus } from "@loadout/shared";
import type { CoreContext } from "../context";
import { AppError } from "../errors";
import { ensureDir, removePathSync, statOrNull, writeFileAtomic } from "../util/fs";

const SCRIPT_FILE = `${CLI_BINARY_NAME}.mjs`;
const STAGED_FILE = `.${SCRIPT_FILE}.staged`;
const STAMP_FILE = ".version";
const WINDOWS_LAUNCHER = `${CLI_BINARY_NAME}.cmd`;
const FALLBACK_RUNTIME = "node";
const EXECUTABLE_MODE = 0o755;
const ENV_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;
/**
 * The SQLite module still prints an "experimental" notice on every start. Agents read stderr as
 * the error channel, so the launcher keeps runtime notices out of it.
 */
const QUIET_ENV = "NODE_NO_WARNINGS";
const QUIET_VALUE = "1";
const GENERATED_NOTE = `Generated by ${APP_NAME}. Rewritten on every app start - do not edit.`;

export type LauncherPlatform = "posix" | "win32";

export interface LauncherInput {
  scriptPath: string;
  runner: { command: string; env: Record<string, string> } | null;
}

export interface CliPublisher {
  /** Make the bundled CLI available to agents. Throws when it could not be verified. */
  publish(): Promise<CliStatus>;
  status(): CliStatus;
}

const shellQuote = (value: string): string => `'${value.replaceAll("'", "'\\''")}'`;
/** `%` starts a variable in batch files and `"` cannot appear in a Windows path anyway. */
const batchQuote = (value: string): string =>
  `"${value.replaceAll("%", "%%").replaceAll('"', "")}"`;

const isFile = (path: string): boolean => statOrNull(path)?.isFile() ?? false;

function runnerEnv(runner: LauncherInput["runner"]): [string, string][] {
  return Object.entries(runner?.env ?? {}).filter(([name]) => ENV_NAME.test(name));
}

/**
 * The app's own runtime runs the script, so agents need no Node install. Should the app have been
 * moved or removed since, `node` from PATH is the fallback rather than a dead launcher.
 */
export function posixLauncher({ scriptPath, runner }: LauncherInput): string {
  const lines = [
    "#!/bin/sh",
    `# ${GENERATED_NOTE}`,
    `${QUIET_ENV}=${QUIET_VALUE}`,
    `export ${QUIET_ENV}`,
  ];
  if (runner) {
    const env = runnerEnv(runner).map(([name, value]) => `${name}=${shellQuote(value)}`);
    const run = [...env, "exec", shellQuote(runner.command), shellQuote(scriptPath), '"$@"'];
    lines.push(`if [ -x ${shellQuote(runner.command)} ]; then`, `  ${run.join(" ")}`, "fi");
  }
  lines.push(`exec ${FALLBACK_RUNTIME} ${shellQuote(scriptPath)} "$@"`, "");
  return lines.join("\n");
}

export function windowsLauncher({ scriptPath, runner }: LauncherInput): string {
  const lines = [
    "@echo off",
    `rem ${GENERATED_NOTE}`,
    "setlocal",
    `set "${QUIET_ENV}=${QUIET_VALUE}"`,
  ];
  if (runner) {
    lines.push(`if not exist ${batchQuote(runner.command)} goto fallback`);
    for (const [name, value] of runnerEnv(runner)) {
      lines.push(`set "${name}=${value.replaceAll("%", "%%").replaceAll('"', "")}"`);
    }
    lines.push(`${batchQuote(runner.command)} ${batchQuote(scriptPath)} %*`);
    lines.push("exit /b %ERRORLEVEL%", ":fallback");
  }
  lines.push(`${FALLBACK_RUNTIME} ${batchQuote(scriptPath)} %*`, "exit /b %ERRORLEVEL%", "");
  return lines.join("\r\n");
}

export function createCliPublisher(
  ctx: CoreContext,
  platform: LauncherPlatform = process.platform === "win32" ? "win32" : "posix",
): CliPublisher {
  const binDir = ctx.paths.binDir;
  const scriptPath = join(binDir, SCRIPT_FILE);
  const stagedPath = join(binDir, STAGED_FILE);
  const stampPath = join(binDir, STAMP_FILE);
  const launcherPath = join(binDir, platform === "win32" ? WINDOWS_LAUNCHER : CLI_BINARY_NAME);

  function readStamp(): string | null {
    try {
      return readFileSync(stampPath, "utf8").trim() || null;
    } catch {
      return null;
    }
  }

  function status(): CliStatus {
    const version = readStamp();
    const published = version !== null && isFile(scriptPath) && isFile(launcherPath);
    return { published, path: launcherPath, version: published ? version : null };
  }

  /**
   * Whatever happens next, an older stamp must not vouch for files we are about to replace.
   * Each step is a weaker way of saying "not usable"; when none works, publishing stops.
   */
  function invalidate(): void {
    const attempts = [
      () => removePathSync(stampPath),
      () => truncateSync(stampPath, 0),
      () => removePathSync(scriptPath),
    ];
    for (const attempt of attempts) {
      try {
        attempt();
        if (readStamp() === null || !isFile(scriptPath)) return;
      } catch {
        // Try the next, weaker way.
      }
    }
    throw new AppError("IO", `Could not replace the published command-line tool in ${binDir}.`);
  }

  function isCurrent(bundledPath: string): boolean {
    const current = status();
    return (
      current.published &&
      current.version === ctx.host.appVersion &&
      statOrNull(scriptPath)?.size === statOrNull(bundledPath)?.size
    );
  }

  async function publish(): Promise<CliStatus> {
    const bundledPath = ctx.host.bundledCliPath;
    if (!bundledPath) return status();
    if (isCurrent(bundledPath)) return status();

    ensureDir(binDir);
    invalidate();
    try {
      copyFileSync(bundledPath, stagedPath);
      const expected = statOrNull(bundledPath)?.size;
      const copied = statOrNull(stagedPath)?.size;
      if (expected === undefined || expected === 0 || copied !== expected) {
        throw new AppError("IO", "The command-line tool was not copied completely.");
      }
      renameSync(stagedPath, scriptPath);
    } catch (error) {
      removePathSync(stagedPath);
      throw error;
    }

    const input: LauncherInput = { scriptPath, runner: ctx.host.nodeRunner };
    writeFileAtomic(
      launcherPath,
      platform === "win32" ? windowsLauncher(input) : posixLauncher(input),
    );
    if (platform === "posix") chmodSync(launcherPath, EXECUTABLE_MODE);

    // Last on purpose: the stamp is the promise that everything above is in place.
    writeFileAtomic(stampPath, `${ctx.host.appVersion}\n`);
    ctx.log.info(`Published the command-line tool ${ctx.host.appVersion} to ${binDir}`);
    return status();
  }

  return { publish, status };
}
